### ISSUE TITLE
Problem importing react-f1.

### ISSUE THREAD

**Issue by ReGGaeBOSS** [Jam3/react-f1#14]
Hi,

Having trouble importing the module. The issue seem to be with a return at line 123. The issue seems to be that I am excluding node_modules from my babel-loader, is it possible to fix this without including node_modules in the loader or adding an other loader just for handling react-f1? (using webpack)

See this img for error msg: http://puu.sh/nEj16/3a1f04cc41.png

**Comment by mikkoh** [comment]
Did you get this figured out? I actually don't use webpack so I'd have to look into this more.

**Comment by ReGGaeBOSS** [comment]
Not really. Since I am importing the module to my main (app.js) it should also be run through the babel-loader. A friend who also use webpack tried importing it to a exisiting working project and got the same error.

Here is how my config looks:
Dependencies: http://puu.sh/nEUSY/1d7e3cf7cc.png
webpack.config.js: http://puu.sh/nEUSY/1d7e3cf7cc.png
I also have a .babelrc in my root folder with presets for es2015, react and stage-0

**Comment by Martin-Pitt** [comment]
I'm also having issues.

The problem seems to be this module has not been built.

Serving the raw source doesn't make any sense in the wider NPM economy. node_modules should really always contain final/transpiled code.

See: http://stackoverflow.com/questions/31822593/import-a-module-from-node-modules-with-babel-but-failed

**Comment by mikkoh** [comment]
Hmmm... Yeah maybe I could do a transpile to a `bundle.js` file on npm prePublish or install. I was talking with @mattdesl and his only comment was that it might be nasty during dev if you're doing `npm link`. He also suggested another solution would be to use:

https://www.npmjs.com/package/ify-loader

Again I have to apologize because I haven't worked with webpack. Anyway... If there's anything that can be done to expedite fixing this I'll gladly accept PR's. Today and yesterday I've been on a lieu day from work trying to spend some time with family.

**Comment by Martin-Pitt** [comment]
I think I managed to hack my webpack configuration to add `react-f1` as a special exception into the babel loader:
```
			{
				test: /\.js$/,
				loader: 'babel',
				query: {
					cacheDirectory: true,
					presets: ['es2015', 'react'],
					env: {
						start: {
							presets: ['react-hmre']
						}
					}
				},
				exclude: /node_modules\/(?!react-f1)/
				// include: path.resolve(__dirname, 'app')
			}
```
(commented out include and added exclude)
Swapping from whitelist to blacklist probably screwing up my project a little, but it is compiling into a valid bundle.js now at least.

On the other hand, react-f1 doesn't seem to be working for me, which is probably unrelated, I'm new to it and wanted to give it a go. Not sure why it is just constantly showing as `display: none` instead of using the idle state I created and told it to `go=` to.

**Comment by mikkoh** [comment]
@Martin-Pitt yeah it'll do `display: none` if states, transitions, and go aren't defined.

I've been trying to think of the best way to handle when everything required isn't defined. My thought was that from a performance standpoint it might be best to at least have the dom rendered but not displayed until animations are good to go.

I'm still debating doing a transpiled builds on `npm i`

**Comment by mikkoh** [comment]
@ReGGaeBOSS or @Martin-Pitt could you try doing `npm i react-f1@webpack` and let me know if it works how you'd usually work with Webpack.

I'm going to transpile code on `prePublish` just want to make sure everything is working before I push this live.

**Comment by mikkoh** [comment]
Sorry I messed that up... I'll give it a go in a bit again... Publishing completely wrong right now

**Comment by mikkoh** [comment]
I was transpiling to a bundle.js but attempted to transpile the entire folder instead and totally broke everything. I had to go out for a work dinner will fix everything when this is done. Sorry about that

**Comment by mikkoh** [comment]
Sorry @ReGGaeBOSS @Martin-Pitt everything should work if you do `npm i react-f1@webpack`.

If everything looks good to you when using webpack I'll publish under `react-f1`. Please let me know. Thanks again for bringing this up.

**Comment by ReGGaeBOSS** [comment]
Thanks man, will try it when back from work.

**Comment by mikkoh** [comment]
:+1: I'll push this update live then.

**Comment by mikkoh** [comment]
@ReGGaeBOSS so funny thing.. I'm not 100% sure how it was working for you. I actually wasn't transpiling to es2015. Was just using the `react` preset so somehow in webpack it was being transpiled from es2015 -> es5. Or then you were testing and chrome and everything worked fine ;)

Anyway... At `6.0.11` everything should work without any kind of transpiling.
